# Generated by Django 2.0.1 on 2018-01-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testword', '0002_auto_20180128_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='关卡')),
                ('content', models.TextField(help_text='每个字之间用,(英文逗号)隔开', verbose_name='本关字集')),
            ],
            options={
                'verbose_name': '关卡字集',
                'verbose_name_plural': '关卡字集管理',
            },
        ),
    ]
